version: 2

custom-steps:
  - &install-clang
    run:
      name: install clang
      command: |
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -
        apt update
        apt install -y software-properties-common
        apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial main"
        apt install -y build-essential clang-9

jobs:
  build:
    docker:
      - image: ubuntu:xenial
    environment:
      CC: clang-9
      CXX: clang++-9
      LD: clang++-9
    steps:
     - checkout
     - *install-clang
     - run:
       command: |
         make -j

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
