version: 2

jobs:
  build:
    docker:
      - image: grumpycoders/pcsx-redux-build:latest
    environment:
      CC: clang-10
      CXX: clang++-10
      LD: clang++-10
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - run:
          name: submodules
          command: |
            git submodule update --init --recursive
      - run:
          name: Build
          command: |
            make -j 2 all pcsx-redux-tests
            make -C src/mips/openbios -j 2
            make -C src/mips/tests -j 2
      - run:
          name: Test
          command: |
            export GTEST_OUTPUT=xml:${TEST_RESULTS}/
            mkdir -p $TEST_RESULTS
            xvfb-run catchsegv ./pcsx-redux-tests
      - store_test_results:
          path: /tmp/test-results
  coverage:
    docker:
      - image: grumpycoders/pcsx-redux-build:latest
    environment:
      CC: clang-10
      CXX: clang++-10
      LD: clang++-10
      LLVM_PROFILE_FILE: /tmp/llvm_profile/profile-%p.profraw
      BUILD: Coverage
    steps:
      - checkout
      - run:
          name: submodules
          command: |
            git submodule update --init --recursive
      - run:
          name: Build
          command: |
            make -j 2 all pcsx-redux-tests
            make -C src/mips/openbios -j 2
            make -C src/mips/tests -j 2
      - run:
          name: Test
          command: |
            xvfb-run catchsegv ./pcsx-redux-tests
      - run:
          name: Merge code coverage
          command: |
            llvm-profdata-10 merge -sparse /tmp/llvm_profile/profile-*.profraw -o coverage.profdata
      - run:
          name: Convert code coverage
          command: |
            llvm-cov-10 show ./pcsx-redux-tests -instr-profile=coverage.profdata > coverage.txt
      - run:
          name: Upload Code Coverage
          command: |
            bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - coverage
